name: CI

permissions:
  contents: write

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install linter
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0

  build:
    name: Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/checkout@v4
        with:
          go-version: '1.24'

      - name: Build
        run: go build -v ./...

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/checkout@v4
        with:
          go-version: '1.24'

      - name: Run tests with Coverage
        run: |
          go test -v ./...